stages:
  data_ingestion:
    cmd: python data_ingestion.py
    deps:
    - src/data_ingestion.py
    outs:
    - data/raw
    - data/processed
  model_training:
    cmd: python model_training.py
    deps:
    - data/processed
    - src/engine.py
    - src/custom_dataset.py
    - src/custom_model.py
    - src/model_training.py
    outs:
    - model/best_emotion_model.pth
    model_evaluation:
      cmd: python model_evaluation.py
      deps:
      - data/processed
      - src/engine.py
      - src/custom_dataset.py
      - src/custom_model.py
      - src/model_evaluation.py
      outs:
      - 